import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/providers/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html
        lang="en"
        className="scrollbar-thumb-sky-700 scrollbar-track-sky-300 scrollbar-thin"
      >
        <body className={inter.className}>{children}</body>
      </html>
    </SessionWrapper>
  );
}
